name: kilsar_chat
description: "A new Flutter project."
# Prevent publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: "^3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State Management (BLoC)
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.0.0
  equatable: ^2.0.5

  # HTTP Client for AI API integration
  http: ^0.13.5

  # Persistence (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # JSON Serialization
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generators
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  # assets:
    # Add any image or other asset directories here
    # - assets/images/

  # fonts: (if you want custom fonts)
  #   - family: YourFont
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
